name: Manual

on:
  workflow_dispatch:

jobs:
  run-jmeter-test:
    runs-on: ubuntu-latest

    steps:         
        - name: Checkout respository
          uses: actions/checkout@v4

        - name: Build JMeter Docker image
          run: docker build -t jmeter-runner ./docker

        - name: Run JMeter test script
          run: docker run --rm -v ${{ github.workspace }}/Testplans:/Testplans jmeter-runner /Testplans/jpet.jmx

        - name: Upload JMeter Results
          if: success() || failure()
          uses: actions/upload-artifact@v4
          with:
            name: jmeter-results
            
            
        
