name: sample

# on:
#   workflow_dispatch:
#     inputs:
#       test_plan:
#         description: 'JMeter test plan file (.jmx)'
#         required: true
#         default: 'your_test_plan.jmx'
#       extra_args:
#         description: 'Extra JMeter CLI arguments'
#         required: false
#         default: ''

on:
   workflow_dispatch:
       # inputs:
       #    - main

jobs:
  jmeter-latest-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run JMeter Test with Latest Image
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/Testplans:/Testplans \
          justb4/jmeter \
          -n -t /Testplans/jpet.jmx -l /Testplans/jpet.jtl

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-results
        path: /Testplans/jpet.jtl
        
    - name: Log Test Results
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-results
        path: /Testplans/jpet.log
